# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
